wee_slack.py

Default location is ~/.weechat/slack.cache
Saved every 5 minutes to avoid excessive writes
`/slack cacheinfo` shows # of messages in in-memory copy
`/slack cachenow` saves the cache to disk immediately
`/slack uncache` removes the current channel from the in memory cache AND saves to disk immediately
¯\_(ツ)_/¯ and whatnot shoudl work now. there are likely bugs here, so open an issue if you see any.
this was a workaround for weechat returning incomplete data when calling curl (even the internal libcurl)
dropping support for weechat < 1.1

Adds caching .UTF-8..

---

wee_slack.py

Plugin wouldn't connect because `user.color_name` was undefined

Fix errors when colorize nicks is off

---

wee_slack.py

JSON decoding errors raise ValueError instead of IOError. In such
cases, the best is to just act as if there was no cache previously.
Signed-off-by: Antoni Segura Puimedon <toni@midokura.com>

Handle JSON decoding errors

---

wee_slack.py

This fixes the #16 problem for me. 
buffers.pl appears to depend on the color not being set in a channel name in order to properly set the hotlist_* colors. Previously the color was being set to default, this change stops setting any color if channels_not_on_current_server_color isn't set.

Fix buffers.pl hotlist colors

---

wee_slack.py

To use on OSX:
weechat:
/set plugins.var.python.slack_extension.trigger_value "(a good random string)"
iterm2 Preferences > Profiles > Advanced > Triggers > Edit:
Regular Expression = "(the same good random string from above):(.*)"
Action = "Run Command"
Parameters = "open https://\1"

Open channels trigger

---

wee_slack.py

These two commands are aliases for one another, and should work in both
private and public channels in Slack. Technically, there's also an
!everyone command, but that isn't implemented here.

linkify_text: Add support for "@group" and "@channel".

---

wee_slack.py

This fixes that `/slack back` and `/slack away` were not updating user presence status by adding support for `manual_presence_change` message type from slack.  Before the fix, this would appear in the slack-debug channel:
```
DEBUG: Function not implemented: manual_presence_change
{u'event_ts': u'REDACTED', 'myserver': 'REDACTED', u'type': u'manual_presence_change', u'presence': u'active'}
```

fixed that /slack (away|back) didn't update status

---

wee_slack.py

process_channel_archive failed to look up the server before
referencing it, leading to backtraces.

Typo in process_channel_archive

---

wee_slack.py

Previously, weechat would not complete @-prefixed nicks, fix that, and
make it so that if you complete on an already-full nick, wee-slack
adds a prefixing @, leading to a slack highlight.

Improve nick completion

---

wee_slack.py

Before:
```
input *.<http://foo.com|foo.com>
output http://foo.com
```
After
```
input *.<http://foo.com|foo.com>
output *.http://foo.com
```
This isn't super pretty, but it's better than losing the text.

Include any text that comes before/after refs in the output text.

---

wee_slack.py

Previously, we would not unfurl responses to our own messages, which
meant we ended up with messages like "<@U12341|foo>: hi" instead of
"@foo: hi". This fixes that.

Centralise handling of unfurling a bit and unfurl replies

---

wee_slack.py

Running this from a server buffer makes no sense, so output an error
if you do that.

Require /slack distracting to be run from a channel buffer

---

README.md
wee_slack.py

Weechat has (since version 0.3.7) a builtin method for plugins to
download from URLs. This commit replaces the use of the curl command
with this. There are two main reasons for doing this:
- When using an external command, the arguments are visible to all
users of the machine, including the token for connecting to Slack.
- It removes the need to depend on curl.
This also makes #78 unnecessary.

Use weechat for requests instead of curl

---

wee_slack.py

If a channel is muted, don't show any activity for it, unless you're
explicitly mentioned.
Fixes: #25

Handle muted of channels by not showing activity for them

---

wee_slack.py

Some messages are already of type unicode when sent into buffer_prnt.
This makes message.decode fail with the following error:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in
position 76: ordinal not in range(128)

Only decode messages if they are not already unicode

---

wee_slack.py

The weechat short_name property is a non-coloured string (according to
discussion on #weechat), so don't add any colours to it.
Fixes: #74

Stop colouring channels and dmchannels

---

README.md
wee_slack.py

This commit:
- Adds the ability to upload a file to the current slack buffer using
the `/slack upload [file_path]` command
Why?
- This is a very useful feature for people that are trying to fully
replace the slack web app

Add upload capability to slack buffer

---

README.md
wee_slack.py

First off, thank you so much for wee-slack.  It's fantastic.
After I switched to wee-slack, I found that buffers.pl (at least in my configuration) put the slack subdomain in the channel name.  I wanted to trim it down, so instead of this:
I wanted this:
I made this change initially back in March when I started using wee-slack and it's been useful to me, so I thought I would share.
Thanks.

support server aliases, so buffer names are shorter

---

wee_slack.py

The slack client (and we) change `/me foo bar baz` into a `_foo bar
baz_` message.  Translate those messages back into actions when
displaying them.
Fixes: #61

Render _foo bar baz_ as action messages

---

wee_slack.py

When that is set, use it for repeated nick lines.
Doesn't handle bots properly yet, will be easier to do once
https://github.com/rawdigits/wee-slack/pull/49 is merged.
Fixes: #56

Respect weechat.look.prefix_same_nick setting

---

README.md
_pytest/conftest.py
_pytest/data/message-changed.json
_pytest/data/message-deleted.json
_pytest/data/message-normal.json
_pytest/data/message-normal2.json
_pytest/test_process_message.py
_pytest/test_unfurl.py
wee_slack.py

This (mostly) stops using buffer_redraw(), which re-rendered the entire buffer by clearing it and then passing every item in channel.messages through the process_message function.
Weechat uses posix seconds in message timestamps. Slack uses posix seconds + a unique index in case multiple messages come in the same second. In the case where there is only one message for a particular second, we just use hdata pointers to modify that line in the buffer. If we are unlucky and there are multiple messages at the same second that need modification, we fall back to redrawing the buffer.

lots of refactoring for efficiency

---

wee_slack.py

This adds a new channel type for mpdms which formats as `"#first,second,third"`
This includes the current user's username, which we may want to exclude.
Closes https://github.com/rawdigits/wee-slack/issues/133

Add mpdm channel

---

wee_slack.py

Fail to modify previous message if contain non-ascii characters.
`s/test/てすと/`
```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 0: ordinal not in range(128)
```

Fix bug that fail to modify previous message if contain non-ascii characters

---

wee_slack.py

Current version is adds `(edited`) to tail when modifing previous message again.
```
test (edited)
```
`s/test/test/`
↓
```
test (edited) (edited)
```

Change to add ' (edited)' only when rendering

---

wee_slack.py

We need to add the short name as an alias so current_domain_name is
able to figure out which server the current buffer belongs to.
Fixes: #158

Make /slack talk and friends work when server_alias is set

---

README.md
wee_slack.py

A reaction can be added to the last message in the channel by writing
+:reaction:
And removed by writing
-:reaction:
Where reaction is the name of the reaction. This is the same syntax that
Slacks web interface uses.
Additionally, it supports sending a reaction to an earlier message by
prefixing the text with a number. The number is the number of the
message to add a reaction to, counting from the bottom. E.g. 1 is the
last message (same as without a number), 2 is the one before etc.
This fixes #155.

Support adding and removing reactions

---

wee_slack.py

All code paths in this method requires channel_buffer, so we can return
in the start if it is falsy.
This fixes a bug where the here and afk variables were not set, but used
later.
This fixes #150.

Return from update_nicklist if no channel_buffer

---

wee_slack.py

process_im_marked may be called after process_im_close (e.g. when you do
/close in an im window). After process_im_close has run,
channel.channel_buffer is None, which makes the buffer_set fail.
This fixes #138 and #143.

Don't call buffer_set in im_marked if buffer is None

---

wee_slack.py

This also fixes a bug where the server buffer was passed as the
message and the user was set to "New user joined: foo".

Set the user to "--" for new user and new channel messages

---

wee_slack.py

Instead of using the format `$team.slack.com` for the server buffer name,
change it to `slack.$team`. This makes it easier to see that the buffer is
a slack buffer.
Additionally, it makes it possible to set options where you specify the
start of the buffer name for all of the slack buffers. For example, it
makes it possible to set the option `logger.mask.python.slack` for
setting a logger file mask for all of the slack buffers.
This is the change I suggested in https://github.com/rawdigits/wee-slack/issues/144#issuecomment-202512332. I figured I'd make a PR for it, so it's not forgotten.

Prefix the server buffer name with slack instead of suffixing it

---

README.md

This comes up in IRC all of the time and was not very obvious to me either.

Update README to mention location of the API token required

---

README.md
wee_slack.py

This adds an option of showing who added each reaction. Instead of e.g. `[:smile:1]`, it now shows `[:smile:(@trygveaa)]`.
In case someone thinks this takes up too much space, I made it optional with the config option `show_reaction_nicks`. That defaults to false, which makes the reactions appear just like before.

Show nicks for each reaction

---

wee_slack.py

These are the same as what the irc plugin sets, and can be used in the
logger masks among other things.
This fixes #188.

Set buffer localvars for channel and server

---

wee_slack.py

Utf-8 is already used for names and messages; it's now also the case for topics.

Encode topics in utf-8, not ascii

---

wee_slack.py

```
python: stdout/stderr: Traceback (most recent call last):
python: stdout/stderr:   File "/home/bendem/.weechat/python/autoload/wee_slack.py", line 344, in buffer_input_cb
python: stdout/stderr:     channel.send_message(data)
python: stdout/stderr: AttributeError: 'NoneType' object has no attribute 'send_message'
python: error in function "buffer_input_cb"
```

Fix error when sending messages to server query

---

wee_slack.py

This supports adding additional tags to enable notification_center.py to push said tagged notifiers to osx' notification center.
In response to: https://github.com/rawdigits/wee-slack/issues/211
It feels like there is/could/should be a better way to do this? Could just be my complete lack of full knowledge around this plugin.
I originally had settings to enable/disable highlighting, as well as customizing the highlights, beyond the ones you set in weechat's `irc.conf`. This however, proved to be useless as the notification_center.py plugin simply hooks into those existing highlights. Interestingly enough, though; `@here`/`!here` mentions in the channel WILL notify, perhaps that was already built in from the start and I missed that.
At any rate, please let me know where changes need/should …

Support passing additional tags to enable notification_center.py

---

wee_slack.py

If you have multiple tokens, it can be hard to figure out which one is
causing an error, so print out the first ten characters to help
identify the problematic one.
Fixes: #163

Print out first ten characters of erroring tokens

---

wee_slack.py

Instead, remove them from the list of channels to hide in the plugin config and save the config.

stop trying to hide channels that no longer exist

---

wee_slack.py

We were parsing mpdm channel names during initial startup, but not when a new one was opened and we received a process_group_joined from slack. We now classify them as mpdm in both places for consistency. Also changed the seperator from "," to "|", because the comma caused problems with the distracting channels setting.

consistently open mpdm the same way by handling the process_

---

README.md
wee_slack.py

This addresses #227 and allows the use of Slack slash commands, as below.
Simply prepend `/slack slash` to whatever you'd run via the official clients, and your command will be run. Example:
`/command arg1 arg2 arg3` simply becomes `/slack slash /command arg1 arg2 arg3`.
I've found it helpful to create an alias of `/command` => `/slack slash command` via weechat for the ones I use.

Add support for slash commands

---

_pytest/test_unfurl.py

This provides nicer granular test cases rather than one whole test that
fails.
Just trying to get myself a bit more acquainted with the codebase before I make larger more meaningful contributions. :)
For context, the difference is:
```
_pytest/test_unfurl.py::test_unfurl_refs PASSED
```
vs
```
_pytest/test_unfurl.py::test_unfurl_refs[case0] PASSED
_pytest/test_unfurl.py::test_unfurl_refs[case1] PASSED
_pytest/test_unfurl.py::test_unfurl_refs[case2] PASSED
_pytest/test_unfurl.py::test_unfurl_refs[case3] PASSED
_pytest/test_unfurl.py::test_unfurl_refs[case4] PASSED
_pytest/test_unfurl.py::test_unfurl_refs[case5] PASSED
_pytest/test_unfurl.py::test_unfurl_refs[case6] PASSED
```

Leverage pytest.parametrize for test_unfurl

---

wee_slack.py

There are two problems with this API request:
1. According to https://api.slack.com/methods/channels.join, "user" is
not a valid argument.
2. The hash table lookup in the removed line of code is destined to fail
anyway, because `self.name` here refers to the channel name, which
is not present in the `users` **SearchList()** instance as it maps
usernames to the Slack API user IDs. Indeed, this causes the call to
`users.find(self.name)` to return `None`, causing an
AttributeError to be raised.
Fixes #190.

Remove unnecessary channels.join API request

---

wee_slack.py

This _should_ make it impossible for the wrong thing to happen with buffers. Every time a new buffer is opened, the hashtable will be updated, so messages to the wrong person via a bad cache should no longer happen.
**tested by closing lots of DM buffers and then sending messages. I was able to trigger the behavior by closing 100 DMs and then opening one, which would result in my first message going to the wrong person.

Update hashtable on buffer open

---

wee_slack.py

Not sure if there's a better way to detect this, but doing things such as `/buffer #foobar` or `/window up`, etc, shouldn't be triggering Slack typing notifications since I'm just happily navigating around my terminal. So it seems like just ignoring if the input begins with `/` is reasonable.

typing: don't trigger typing indicator from weechat commands

---

wee_slack.py

This PR does a few things:
1) Nicklists no longer change based on presence. The distinction between here/away still exists in usernames for open DM channels, but not for nicklists. The cpu overhead for maintaining every nicklist in many channels was very high for channels/teams with many users, and the value of having a nicklist in Slack is probably low.
2) Only load channel history the first time you switch to that buffer. In previous versions, we loaded channel history for each of your current slack channels. This makes startup time pretty bad for people on many teams or in many channels. This change took my average start time from > 60 seconds to about 10 seconds to connect to 44 Slack teams.
3) I finally switched the different channel objects to use kwargs, which makes them much …

Performance improvement and minor refactor

---

wee_slack.py

in order to upload files with spaces in filename, escape the filename if spaces is found.

Handles upload with spaces in filename

---

wee_slack.py

via @ToxicFrog:
All the per-setting globals are replaced with a single global object,
'config'; its attrs are the weechat settings. They're automatically
updated on config change, and the setting names and defaults are
specified as part of a map in the PluginConfig class definition.
To add a new setting, add the setting name and default to
PluginConfig.settings, and if it's not a boolean, add an appropriate
PluginConfig.get_ method as well.

Refactor the way settings work + fixes

---

wee_slack.py

Set localvar which is picked up by weechat and which should be picked
up by `screen_away.py` and similar tools.
Thanks to Tor Hveem (@torhve) for inspiration.
Fixes: #161
This should also make /away D

Add support for /away

---

README.md

The previous page only links to the new style application tokens, which do not work.

Update token link

---

_pytest/conftest.py
wee_slack.py

- Received messages are now properly detected whether they use _
wrapping or the me_message subtype
- Sent messages are now properly rendered as actions in the buffer
- Message replies in general are now handled by process_message(), and
thus should have formatting consistent with normal messages

Fix /me handling for sent and received messages

---

wee_slack.py

This translates `*` into bold and `_` into underline (since most IRC clients don't support italics). It also properly handles outgoing `\x02` and `\x1F` characters.

Translate slack formatting codes to/from IRC formatting codes

---

wee_slack.py

This removes the colorize_nicks setting, instead relying on weechat's built in settings for nick colours; it also moves from `irc_nick_color_name` to `nick_color_name`.

Defer nick colourization to weechat's built in support

---

wee_slack.py

fixes the join command because joining channels is useful. sometimes.

wrong var name

---

wee_slack.py

This changes wee_slack to only use unicode strings internally, and encode/decode to utf-8 when it sends/receives data, which fixes some unicode errors that's been happening e.g. when editing non-ascii messages (hopefully fixes all unicode issues, but can't guarantee that). Some info from the first commit:
> This changes all strings to be unicode strings in an attempt to handle
> unicode better. The idea is to use unicode everywhere internally in
> wee_slack and decode/encode where data is received/sent to/from
> wee-slack.
> 
> That means we have to decode strings received from weechat or slack and
> encode strings we send to them. This way encoding and decoding is done
> on specific places, and if done everywhere, we should not get any
> unicode errors.
I've tested this briefly, but not …

Proper support for unicode

---

README.md
wee_slack.py

Add in a command called `/slack status`, allowing users to set or clear their Slack Status. 
Usage:
`/slack status [:emoji:] [Status message]`

Add command for setting Slack Status

---

wee_slack.py

Today I learned that sometimes, rather than the key missing, it has the value
None. In this case, (key in dict) is true!
This fixes an issue where, if the backscroll of a channel contained such a
message, it would throw while fetching the backscroll and cut off without
fetching all of it.

Fix channel history not appearing when an earlier message has 'text': None

---

README.md
wee_slack.py

This should make nick colors work in weechat < 1.5 again by using either the info_name `irc_nick_color_name` or `nick_color_name` depending on the version. It also removes the outdated docks for the colorize_nicks option which doesn't exist anymore.
Replaces #318 since the last comment there never was addressed.
It would be great if someone with weechat 1.3 or 1.4 could verify that this actually fixes the issue.

Fix nick coloring in weechat < 1.5

---

.gitignore
_pytest/conftest.py
wee_slack.py

Not everything that needed to be mocked out was, and there was also an
issue with every instance of PluginConfig sharing the same mutable
settings field and thus stomping on each other if you initialized more
than one in the same test.

Fix the tests

---

wee_slack.py

The Slack API spec says we should ignore markdown formatting if this key is unset or false, and I've seen a few (rare) messages where it looks like not supporting this went wrong.

Disable formatting for messages with `mrkdwn` unset

---

wee_slack.py

This fixes the issue raised in #396.
On initial creation of slack channels, I've updated the code to kick off a request to the 'channels.info' for each channel. Upon completion of the info request I've added a handler that will set the unread count on the channel and if the unread count is greater than zero, it will add the channel to the hotlist. 
I've re-used the slack channel property 'unread_count_display' (which no longer exists) so that existing functionality that relied on that property will not fail. In this PR, I've only narrowly focused on the 'unread_count' property of the channel, but this channel info request could probably be used for more in the future.
Thanks!

call channel info on channel open to set unread count and update hotlist

---

wee_slack.py

Specifically, if you have debugging on you will get an exception for every single character typed in a thread, which makes debugging anything else kind of aggravating.

Don't send typing notifications for threads, since Slack doesn't like that

---

wee_slack.py

Properly escape <&> when sending messages to Slack.

---

wee_slack.py

Thread buffers open, but buffer variables are not set due to an AttributeError.
Fixes: 78af3f21b378 ("Re-add setting of localvar_set_nick")

Fix opening thread buffers

---

wee_slack.py

While the commit 6718e2f fixed buffers not appearing in the hotlist,
after it the number of new messages for each buffer was gone. This makes
the number of messages for each buffer shown again.

Set correct number of unread messages in hotlist

---

_pytest/test_linkifytext.py
wee_slack.py

As pointed out by @auscompgeek on IRC, the HTML entity-encoding is broken. If you send e.g. `<test>`, it will be printed as `&amplttest&ampgt` in wee-slack and `&lttest&gt` in the web client.
We have to replace the & before we replace < and >, otherwise the & in &lt; and &gt; are going to be replaced. Additionally, we need to end the sequences with ; which was missing.

Fix HTML entity-encoding of outgoing messages

---

wee_slack.py

Instead of just checking that bot_id is not None, check that it exists
in the list of bots. This prevents a KeyError when trying to access a
bot that doesn't exist in the list.
This KeyError would happen if you use a reminder. The message from
slackbot then has bot_id B01 which is not in the list of bots from
rtm.start and gives bot_not_found if trying to look it up with the
bots.info API endpoint.
By ignoring the bot_id we fall back to the user/username, which in the
case of reminders is slackbot, so the name appears just as the other
messages from slackbot.
Fixes #420

Check that the bot_id exists before using it

---

wee_slack.py

This improves rendering when multiline messages are changed or reacted to, by updating each line of the existing message instead of cramming all of the new message into the last line. That means that if the number of lines in the message doesn't change, the message will still be rendered correctly after edits or reactions.
If the number of lines change, the rendering is still improved, however I don't know if it is possible to insert or delete lines in a weechat buffer without re-rendering the whole buffer, so it won't be perfect. If the number of lines of a message decreases after an edit, the extra lines will still be present, but they will be blanked. If the number of lines increases, the first lines will be set as normally, but the last line will contain all of the rest of the lines.

Improve rendering of changes in multiline messages

---

_pytest/test_unfurl.py
wee_slack.py

This fixes a bug where messages of the form `@person I think 3 > 2` end up trying to unfurl everything up to the *last* `>` in the message.

Fix overzealous regex in unfurl_refs

---

wee_slack.py

When links are expanded it sometimes becomes unreadable as the same link is pasted over and over. For example:
The longer the link the worse it gets. This PR avoids repeating the same link over and over:

When expanding attachments avoid rendering same link multiple times

---

wee_slack.py

When we print a message with multiple lines to weechat, we want the nick/prefix to appear on the first line, and no prefix on the subsequent lines.
When this message is handled by weechat, it processes each line of the message separately, and applies a prefix for each line. It seems to me that if the line doesn't contain any tab characters, it should end up with an empty prefix, and this is what happens for me.
However, some users are having issues where both the prefix and the message ends up incorrect (issue #274, #385 and #421), which seems to be related to this.
Additionally, if the message contains a tab character on any of the lines after the first, the part before the tab character would be the prefix for that line, which is completely wrong. I haven't seen that happen, as it seems …

Ensure that all lines printed to weechat specifies a prefix

---

wee_slack.py

This hooks into the weechat commands `/input set_unread` and `/input set_unread_current_buffer` and implements them. For set_unread we iterate over all the channels and mark them as read. For set_unread_current_buffer we mark the current buffer as read.
Fixes #323

Support `/input set unread` and `/input set_unread_current_buffer`

---

wee_slack.py

This gives groups a configurable buffer name prefix, and changes the MPDM static short buffer name prefix to `@`.
Fixes: #410

Make groups and MPDMs distinguishable by prefix

---

README.md

Wanted to debug some changes and noticed that the `/slack debug` command doesn't exist anymore and instead debug mode is enabled via the `plugins.var.python.slack.debug_mode` setting. Guessing this is related to the refactoring mentioned in #379. If the command is being added back though then my bad, feel free to close this PR.

Update documentation on enabling debug mode

---

wee_slack.py

This fixes `/thread` to obey the `switch_buffer_on_join` setting.
Ref: #377

Switch to thread buffer on open if configured

---

_pytest/conftest.py
_pytest/test_topic_command.py
wee_slack.py

This refactors the topic command, and makes it behave the same way as it does on IRC. The fixes include:
- `/topic` prints the topic instead of clearing it
- `/topic #channel` prints the topic for that channel in that channels buffer instead of setting the topic to #channel
- `/topic #channel [...]` for a channel that doesn't exist gives a proper error message
The patch also removes some unused code, refactors the logic and removes the `/slack topic` command, since using `/topic` should suffice.
The reason it returs WEECHAT_RC_OK_EAT when the channel isn't found, is so weechat doesn't print an error message such as:
irc: command "topic" must be executed on irc buffer (server or channel)
Fixes #405

fix: Make /topic behave the same way as on IRC

---

wee_slack.py

- The DM error was caused by not specifying `return_im`
(https://api.slack.com/methods/im.open#arguments) in the request which
led to `unread_count_display` not being included in the response and a
KeyError in `handle_imopen`
- The MPDM error was caused by using "name" instead of "channel" for the
channel ID (https://api.slack.com/methods/groups.info#arguments) in the
request which led to an error response and a KeyError in
`handle_groupsinfo`

Fix errors when joining DMs and multiparty DMs

---

_pytest/test_utf8_helpers.py
wee_slack.py

This adds a decorator we can put on functions called from outside of the script (e.g. callbacks from weechat), so we don't have to call `decode_from_utf8` on the arguments we use. It also adds tests for the UTF-8 helpers.

Add a decorator for decoding function arguments from UTF-8

---

wee_slack.py

This fixes Glowing Bear not grouping wee-slack's buffers by server correctly.
Thanks to Bun on freenode for reporting this issue.

Set the server buffer variable on server buffers

---

wee_slack.py

- Fix a regression from 95fa084893660b655388604084f082a080f1ba32 that disabled the nicklist in multi-person direct
messages

Display nicklist in MPDM messages

---

wee_slack.py

This allows /query to accept @username arguments as if they were username.
Since the completion command prefixes @, even in case of /query, it can help to allow those rather than being obliged to remove it manually

Allow query with @'es

---

wee_slack.py

This list is not populated anymore, so we shouldn't show it at all.

Remove the nicklist from the team buffers

---

wee_slack.py

This adds a hilight on team identifier in Slack.
The reason is that the api sometimes gives those identifiers without "@" prefix, especially in case of hooks (the bug also appears on slack non-web clients).
Since the identifier is quite "unique" there is almost no risk of unwanted hilights

Hilight team identifier in slack

---

wee_slack.py

- Many IM clients that support alerting the receiving user that you're
typing include an option to disable this behavior. This commit adds
the `send_typing_notice` boolean option. When it is false
`typing_notification_cb` is not registered for the
`input_text_changed` Weechat signal. By default this option is
true.
https://xkcd.com/1886/

Add option to disable sending typing notification to Slack

---

wee_slack.py

Group DMs shouldn't be displayed just because `is_member` is `True`, because it always will be. Instead, if a channel/DM/whatever has an `is_open` property, use that, and only fall back to `is_member` when `is_open` isn't present (such as for channels).

Hide closed group dms

---

README.md
wee_slack.py

This allows you to send messages starting with / or messages like s/a/b/
and +:test: as normal text messages instead of performing the action
they normally would. This is done by prefixing the message with / or \,
and then the prefix character is removed from the resulting message.
Allowing / as a prefix, so you can write e.g. //slack is the normal way
to send messages starting with / in weechat. Using \ instead is added
for the other special messages (e.g. /+:test: is interpreted as a
command, so you have to write \+:test: instead). If you want to write a
message starting with \, just start it with \\.

Allow sending special messages by escaping them with / or \

---

README.md
wee_slack.py

`command_talk` can now accept multiple arguments, which allows commands
like `/query user1 user2` to open a MPDM with user1 and user2.

Add ability to open multiparty DMs with /query and /slack talk

---

_pytest/test_unwrap_attachments.py
wee_slack.py

- Adds tests for `unwrap_attachments`.
- Adds a newline between attachments, when there are multiple attachments.
- Prevents links from being printed twice when title_link and from_url are the same link, and that link doesn't appear in the message text (if it appears in the message text, that is already handled with #387).

Attachment tests and minor fixes

---

_pytest/test_unfurl.py
wee_slack.py

When you write multiple words separated by dots, or email adresses, Slack will turn those into links. Wee-slack will display this as `text (url)`, where url is just the text with http:// or mailto: prefixed. This makes the text hard to read, and might not even make sense (e.g. when writing server names or user@hostname).
When you receive such an url, the alt text of the url will be the original text. This means that we can check if the url is just the alt text with a protocol prefixed. If it is, we should just print the alt text and ignore the url.
I guess some people may want the urls, so they are able to click the links. And since it removes information coming from slack, I made it into an option instead of making it the default.

feat: Remove Slacks auto prefixing of url protocols

---

wee_slack.py

In large Slacks, channel membership isn't included in the initial channel
info, but in channelsinfo messages sent after connection. This fixes an
issue where most users would not ever show up in the nicklist when
connecting to such slacks.

Handle memberlist updates in channelsinfo message

---

wee_slack.py

This exception is expected to some degree and does not affect the functioning
of wee-slack. With this change, it will no longer appear in the log.

Suppress SSLWantReadError errors

---

README.md
wee_slack.py

Partly addresses #135. This restores some OAuth logic that was lost in a large merge, and it updates the lost logic to be compatible with the latest wee-slack code.
The old logic had simply printed the Slack token to the buffer. I added a new feature: the new logic now automatically appends the token to the "plugins.var.python.slack.slack_api_token" setting and tells the user to restart weechat.
There are two more missing features after this which I propose to add:
1. Fix the OAuth redirect failure. Open a local webserver listening on a random available port, then include the `redirect_uri` parameter to redirect the auth flow back to localhost (if possible, this'll require research and maybe help from you to configure the wee-slack app on slack.com)
2. Update the `config_changed` callback …

Restore OAuth support

---

wee_slack.py

Since recent changes in Slack, usernames can no longer be set directly, and
are instead inferred from the email address. This is not particularly useful,
so the recommendation is to instead use display_name. display_name may have
spaces in it, however, which confuses tab completion.
With this change, wee-slack uses display name for both display and completion,
after first stripping all whitespace from it. Ref linking (via linkify_text)
ensures that @mentions continue to work properly even when this whitespace
removal means that the name being @mentioned locally doesn't match the "real"
username.

SlackUser: use profile.display_name if available

---

wee_slack.py

Big teams will make big json and go over the limitation of 4k per websocket message.

Temporary fix user presence subscription crashing big teams

---

wee_slack.py

The function was renamed at some point without renaming the hook signal,
so weechat would print an error when exiting.

Fix quit callback function

---

wee_slack.py

Autocompletion of nicks does not work in virtual Thread channels, because `nick_completion_cb` looks for a set of members and a team to pull user profiles from.
This makes them work, by pulling members set and team from the thread's parent message's channel.
Note that `SlackThreadChannel.members` will not be the same as the users who have participated in the thread. It is the members of the parent channel, which seems better for autocompletion's sake since users might want to mention others to bring them into the thread.

Include members set and team in SlackThreadChannel

---

wee_slack.py

This check was done when generating complete nicklist, but not when
updating a single user. Deleted users are still part of the member list
of a channel, if they don't leave the channel first. This caused a
deleted user to be inserted into the nicklist when processing a joined
channel message or when receiving a presence change for that user.
When investigating this, I saw that we still receive presence change
events for deleted users if we subscribe to them. We might want to
filter out the deleted users when generating the list of users to
subscribe to.

Don't add deleted users to the nicklist

---

wee_slack.py

* Fixes display names for 'app' users,
in before it'd be displayed as "bot :]"
and now it's "-{display name}-".

Reorder get_sender bots vs user checks

---

wee_slack.py

This makes a big difference for larger teams where rtm.start can time
out just due to Python's strings being immutable.
Fixes: #516

Use StringIO instead of string concatenation

---

wee_slack.py

The work in #318 correctly gets most users' nick coloring, but this information was previously discarded for the user's own messages.
This fix correctly uses the sender's own `weechat.color.chat_nick_self` preference for self-sent messages.
Fixes #527

Fix self-nick color in messages

---

.flake8
.travis.yml

__flake8__ tests currently flag __server__ as an undefined name twice in __wee_slack.py__.  Undefined names can raise a __NameError__ at runtime.  This PR adds flake8 testing to our Travis test runs.  ~~This PR will continue to fail until the two undefined names below are resolved.~~
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./wee_slack.py:3316:13: F821 undefined name 'server'
server.buffer_prnt("Usage: /slack slash /someslashcommand [arguments...].")
^
./wee_slack.py:3417:13: F821 undefined name 'server'
server.buffer_prnt("Usage: /slack status [status emoji] [status text].")
^
2     F821 undefined name 'server'
```

Use flake8 to find undefined names

---

wee_slack.py

If you have multiple windows in weechat, you get (by default) one typing
bar per window. Previously, the bar used the globally active channel
(the active channel in the active window) for all the bars, so all the
bars would show the same info. This changes it to use the active channel
for the window the bar is in.
The callback name is changed to include (extra), as that is necessary
for getting the active buffer for each window as an argument to the
callback function.

Fix typing indicator when having multiple windows

---

wee_slack.py

See issue #573
The proxy can be configured within weechat using /proxy command and weechat.network.proxy_curl settings.
Upload has not be tested because I didn't have anythin to upload. But it should work

add http proxy support

---

_pytest/test_eventrouter.py
_pytest/test_everything.py
_pytest/test_processteamjoin.py
wee_slack.py

These missing callbacks are not really errors or exceptions, and we
don't need to implement all of them. Raising an exception makes the
users think something isn't working, and is confusing.

Don't raise exception on missing event callbacks

---

wee_slack.py

Looks like slack recently changed the format for upload messages, this is a relatively quick and dirty fix to include the uploaded file title and url in the messages.

Adding support for new slack upload message style

---

wee_slack.py

This notifies (or automatically opens) threads concerning the user:
- When someone mentions him in any subthread
- When a response is given to a thread in which the user participated, but the thread was closed inbetween
- When a thread is open in response to a message the user wrote.
This implementation works, but is still not complete for the last two cases:
The user may receive a "notifiable" thread message associated to a channel which he didn’t open yet (since last reboot for instance), and won’t be notified of that until he goes to open the channel and "fetches history" (better than nothing, but getting the notification earlier would require fetching the history of the channel as soon as we get notified, which is probably not a good idea)
I think this makes the feature quite usable …

Subscribe threads

---

wee_slack.py

As of for now the `darkgray` color is hard coded inside the plugin for reactions suffixed on messages.
My current terminal background was `darkgray` so it caused a problem :see_no_evil:.
I reckon it would be nice to have a setting to overide this color with a plugin config.
WDYT?

reactions: Add a config parameter to change color of suffixed reacs

---

wee_slack.py

Deleted files don't have `url_private` nor `title` attributes. Their `mode` is set to `tombstone`.
Closes #640

Fix loading history with deleted attachment

---

wee_slack.py

Typing more than 8 characters or hitting tab after a non-space character
in the core buffer causes errors because the buffer is a SlackTeam
object instead of a SlackChannel.

Fix typing and completion errors in core buffer

---

README.md
wee_slack.py

This adds an "open thread" command using the cursor.
It also adds support for `/thread $id` syntax

Add open thread command with cursor

---

README.md
wee_slack.py

This PR makes a small addition thanks to the new "line message search" feature: it permits to paste in the input the full link to a given message, obtained either by its thread id or by clicking / cursoring it.

Add linkarchive slack command to create a link to a given message

---

_pytest/conftest.py
wee_slack.py

This rewrites modify_buffer_line and modify_print_time (now modify_last_print_time to be more clear) to be much more readable.
modify_buffer_line had a bug where it moved past the first line, causing the line_pointer to be lost so the first line couldn't be updated. This is now fixed.

Fix bug preventing first line in buffer to be changed

---

wee_slack.py

This option allows a user to set a custom color to the (edited) suffix on messages that have been edited.
The default color is set to '095', as it was the former choice.

Add an option to set color of (edited) suffix

---

_pytest/test_formatting.py
wee_slack.py

First and foremost, this prevents formatting going across newlines. Consider this example message:
```markdown
* an item
* another item
```
Clearly, `an item` should not be made bold. Slack doesn't.
This also preserves the original typed message, with `*_formatting_*` characters galore, for a few reasons:
* as a quick fix for #566 until we fix that properly, and
* Slack preserves formatting characters when copy-pasting.
This also prevents formatting going across backticks, such as in the following example:
```markdown
* Run this command: `find . -name '*.exe'`
```

Minor formatting fixes

---

wee_slack.py

This is the same as #549, which I closed originally to work on a more complicated solution that tackled some other thread-related things. With #616 I feel that solution isn't necessary anymore though, and this simple change actually pairs nicely with enabling `thread_messages_in_channel` (but it'll still fix channels not being marked as read regardless).

Include threads when marking latest message as read

---

wee_slack.py

Fixes:
* `wrong arguments for function "buffer_set"` when joining a channel
from the web client
* resolve references (e.g. `<@JHDJFHKDW>`) in topic
I'm still not really happy with the code, seems to me that
using `update_from_message_json` to fill channel attributes is really
dangerous and we should avoid it. I'm not sure what will break if I just
drop the call. Does anyone here know or shall I just drop it and try
running that for a while?

Two fixes of topic handling

---

wee_slack.py

* for details please see: https://api.slack.com/methods/chat.getPermalink

Fix /slack linkarchive command because of an API change

---

wee_slack.py

The 'slackbot' channel has been renamed to 'Slackbot'. 
The channel name change breaks `slack_never_away_cb`, and this PR fixes it.

Fix 'slackbot' name change to 'Slackbot' breaking never_away

---

README.md
wee_slack.py

Hey 👋 
Great plugin!
I had this idea and managed to hack something together: most of the time only the last thread in the channel is the most intriguing one and in those cases there's no need to type out a random id to access it.
This adds the ability to just type:
```
/thread
```
and the last thread in the current channel should be opened if found.

Add ability to open last thread in channel without specifying message id

---

wee_slack.py

Currently files are always uploaded to the main channel, even when
`/slack upload` is run in a thread buffer. This happens because the
`thread_ts` field isn't included in the upload request.
Fixes #672

Upload file to thread instead of channel when in thread buffer

---

_pytest/test_topic_command.py
wee_slack.py

* This change makes sure the /topic command outputs
'Topic for #random is ""' instead of
'Topic for #random is "{'value': ''}"'.

Fix /topic command output

---

wee_slack.py

Attachment fields are not guaranteed to have a title at all.
This fixes in particular slackbot app approval messages, with an
attachment like so:
```json
{
"callback_id": "whitelist_A11BCGM0E_181389840855",
"fields": [
{
"short": true,
"value": ":white_check_mark: *<@U4RPXA42F|davo> approved this app for the team.*"
}
],
"fallback": "Approve or deny the application",
"id": 4,
"color": "#2ab27b"
}
```

Fix attachment fields without titles

---

README.md

When installing on OpenBSD, you need to specify the Python 3 version (not Python 2)

Use Python3 websocket-client

---

wee_slack.py

See https://api.slack.com/reference/block-kit/blocks .
This is used by, among other things, the Polly poll bot, and fixes the issue I brought up in #667.
Is there a function I can use for rendering message formatting?  Right now the poll options include `*text*` and dates: `!date^1572642900^{date_short_pretty} at {time} (Today at 21:15 PM)`

Add implementation of slack layout blocks

---

wee_slack.py

It currently seems to work on threads that are automatically subscribed
(such as by saying something in them or by subscribing in the slack web UI).
Does anyone know what the difference between thread_message and message_replied is?  They both have some processing of thread messages.

Allow subscribing to threads

---

wee_slack.py

This prevents messages being added to buffer 1 when a new thread is opened and the message is already expanded in the parent channel.

Don't notify about threads when they're opened in the channel

---

wee_slack.py

Previously, files with a mode other than "tombstone" were assumed to have a
"title" and "private_url". This is not necessarily the case; in particular,
files with the "hidden_by_limit" (removed from visibility because the
workspace has exceeded its free-tier storage limit) mode have *only* "id" and
"mode". This resulted in a KeyError trying to look up the "title" and
"private_url", and truncated history at the message with that file.
This commit explicitly handles "hidden_by_limit" files, and makes the handling
of any other unknown modes more robust by explicitly checking for "title" and
"private_url" before rendering a message with them.

More robust handling of file modes

---

wee_slack.py

When not using english locale, date could contains non ASCII characters.
Fixes #419

Fix usage of dates with non ASCII characters for Python 2

---

.gitignore
.travis.yml
Pipfile
README.md
docs/contributing.md
requirements.txt

[Pipenv][0] makes it easier to maintain a consistent development
environment for projects using Python. You no longer need to manage
`pip` and `virtualenv` separately, nor deal with the drift and other
issues requirements.txt brings. It enables gaining insights into your
dependency graph, but most importantly - it enables deterministic
builds, which prevents the entire class of "it works on my machine"
problems.
[Pipenv][0] is similar to package managers from other ecosystems, such
as Node.js' `npm` or Rust's `cargo`. Additionally, [Pipenv][0] is an
[officially recommended package manager][1] by the Python project.
This patch brings [Pipenv][0] to the wee-slack project to simplify the
development and contribution experience. Additionally, this patch brings
basic contributing documentation …

feat: use pipenv to manage the development environment

---

wee_slack.py

Well, the commit message is pretty obvious.
I actually noticed this as my terminal highlights the tab since there's new console output.

Don't display the typing indicator for muted conversations

---

docs/Commands.md
wee_slack.py

This was broken in #774 as it checked if there was at least one reply, which is not the case for new threads.

allow new threads to be opened via /thread <THREADID>

---

wee_slack.py

This supersedes #529 and should finally close #526 .
To disable URL unfurling: `/set plugins.var.python.slack.link_previews "false"`, followed by a `/python reload` or a Slack channel close/reopen.
To re-enable, set to `"true"` and the same reload is required.

Add support to disable teammate link previews

---

Dockerfile

The current Dockerfile fails to build as the latest alpine images no longer include a plain `python` package. This change installs the `python3` package instead.

Update Docker image to use python3 package

---

wee_slack.py

I often manually hide buffers.  I don't want to mute them or mark them as distracting, because I still want them to pop up when they get a message, I just want them out of the hotlist/buflist for the time being.  The problem is that when wee-slack reconnects to Slack (usually several times per day), reprinting the messages causes all the buffers to get unhidden again, blowing out the buflist length.  This patch fixes that by avoiding unhiding for `no_log` messages.

Don't unhide buffers when reprinting messages

---

wee_slack.py

I continuously received this error, when started weechat:
```
AttributeError: 'NoneType' object has no attribute 'token'
```
Because tokens list was `['', '']`. And weechat tried initiate connections without tokens.
This small change fix this error.

Validate token not empty, before initiate connection

---

wee_slack.py

An error occurs when:
- running on Python 2.7 (weechat 2.3 on Debian oldstable)
- someone's nick contains non-ASCII characters
Any messages from that person are not displayed, and the core buffer shows the error message:
```
python: wrong arguments for function "string_remove_color" (script: slack)
```
Apparently the reason for this is that on Python 2, `weechat.string_remove_color` fails when passed a Unicode string containing non-ASCII characters.
Moreover, if the string might contain combining characters, CJK, or emoji, then the `len()` of the string is not the same as its width.  `weechat.strlen_screen` should give the right answer, or at least weechat's best guess.

Fix handling of (multiline) messages from non-ASCII nick

---

README.md
_pytest/conftest.py
_pytest/test_topic_command.py
extract_token_from_browser.py
wee_slack.py

This adds support for using the new type of session tokens (the ones starting with `xoxc`) that has replaced the old one.
To use such tokens, you also have to provide the `d` cookie from the browser. Currently this is specified after the token in `slack_api_key`, separated by a colon, e.g. `xoxc-token1:cookie,xoxp-token2`. The way to specify this may (hopefully will) change in the future.
Fixes #844
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#844: Session tokens no longer working](https://issuehunt.io/repos/18410202/issues/844)
---
</details>

Support new session tokens (xoxc tokens)

---

wee_slack.py

When slack return a button message type and a url field is present we
should output the URL.
Fix: #811 and #810

feat(display): Add URL when slack block contain URL

---

README.md

Closes #847 
I believe the WeeChat docs and default directories have changed since README.md was created.

Update Python script instructions in README.md

---

README.md
extract_token_from_browser.py

On the Linux machines I've used, the default profile is suffixed .default, not .default-release.  I'm not sure what systems use .default-release, but preserving it for compatibility seems harmless.
This is actually not enough to get it working for me.  It bails later on: webappsstore.sqlite doesn't have anything with key "localConfig_v2", or anything that even looks like it.  System is firefox 110 on Debian testing.

extract_token_from_browser: widen default profile check

---

Dockerfile

I think the path has changed in the intervening years since this dockerfile was last edited; this new fix appears to work just fine in my tests.

docker: Update script path for wee_slack.py

---

wee_slack.py

It can be difficult to find a specific channel if there are thousands of them in your slack workspace.  This enhancement allows you to filter the channels based on a regular expression.  For example:
`/slack channels support`
returns
```
Channels that match "support":
#customer-support    (not a member)
#it-support-team     (not a member)
#technnical-support  (member)
```

feat: Filter channel list based on regular expression

---

_pytest/conftest.py
_pytest/test_render_message.py
wee_slack.py

Commit 74da30342e8d328fc085d2158e37afda3b908f2c added support for using rich_text blocks to format messages. With this change, the use of replace_string_with_emoji() for text type "emoji" can result in running the replacement twice as replace_string_with_emoji() is also called as one of the last steps in SlackMessage.render().
This works fine in the default case when render_emoji_as_string = "", however render_emoji_as_string = "both" results in output like:
`😄 (😄 (:smile:))`
instead of the intended:
`😄 (:smile:)`
This skips the second call of replace_string_with_emoji() if blocks were rendered earlier in the method.

Make render_emoji_as_string = "both" work with rich_text blocks

---

wee_slack.py

The Slack documentation claims that the “ts” flag on attachments is “An integer Unix timestamp”. However, evidently it can be in milliseconds (i.e., a timestamp multiplied by 1000), causing out-of-range exceptions when trying to feed them to date.fromtimestamp(). This can cause all messages after such attachments to just vanish, as if they were never there, as parsing stops.
Accept both; as a heuristic, the Slack web interface seems to use 100000000000 as a threshold, so we do the same and divide by 1000 if so.

Handle millisecond-level timestamps in attachments

---

slack/commands.py
slack/slack_api.py

The user can now set his presence with:
/slack away
and back with:
/slack back
It's not possible to set a custom status for now.

Set user user presence

---

slack/slack_conversation.py
slack/slack_user.py

When opening a private conversation, show the real name of the user in the status bar instead of an empty status.

conversation: show user real name in title

---

docs/Commands.md
wee_slack.py

It can be difficult to find a specific user when there are tens of thousands of users in your slack team.  This enhancement allows you to filter users based on a case-insensitive regular expression.  For example:
```
/slack users ^.Mason
Users that match "^.Mason"
bmason  (active)
jmason  (inactive)
lmason (active)
SMason  (inactive)
```

feat: Filter users list based on regular expression

---

docs/Options.md
wee_slack.py

When `use_usernames` is true, the username is preferred over the full name or the display name.
Example: `JohnDoe` → `jdoe`

Add option to see the username as the nick

---

wee_slack.py

In newer Python versions, using count/flags on re.sub in positional mode triggers a `DeprecationWarning`:
```
python: stdout/stderr (slack): ~/.weechat/python/autoload/wee_slack.py:2063:
DeprecationWarning: 'count' is passed as positional argument
python: stdout/stderr (slack):   new_message_text = re.sub(old, new, old_message_text, num_replace, f)
```
This commit changes the call to use flags and count in keyword argument mode.

s/ command: fix deprecation warning about positional args in re.sub
