wee-slack/wee-slack

README.md, wee_slack.py
To edit your last message: `s/old/new/`
To delete your last message: `s///`
=> regex style message editing

wee_slack.py
make /query work in slack buffers. per issue https://github.com/rawdigits/wee-slack/issues/42
=> make /query an alias for /join. they are identical to slack.

wee_slack.py
simple fix - don't print username.
=> don't print username in /me and do italics like official clients

wee_slack.py
colorize user names in output like colorize_lines.pl
was going to make colorize_lines work, but lots of annoying things to make that happen. this should work as well.
works for `name` & `@name` & `@name's`
=> colorize nicks in lines like colorize_lines.pl

README.md, _pytest/conftest.py, _pytest/data/message-changed.json, _pytest/data/message-deleted.json, _pytest/data/message-normal.json, _pytest/data/message-normal2.json, _pytest/test_process_message.py, wee_slack.py
Instead of printing a new message with updated text, edited messages now replace the original message in the buffer. Big thanks to @torhve for pointing me toward hdata as a way to modify buffer lines!
=> Improved message handling

wee_slack.py
- Ensures the input prompt will show username as in irc buffers
- Fixes #80
=> Set nick localvar when attaching buffers

wee_slack.py
Somewhat fixes https://github.com/rawdigits/wee-slack/issues/54, at least they're now shown as the right type of activity.
=> Fix up formatting of join/part/topic messages

wee_slack.py
This started as a branch to support reactions, but to do so properly required a number of backend changes. In no particular order:
* Enhanced SearchList class and made much more performant. Added a hashtable to each SearchList that acts as an index for much faster lookup of objects when doing `.find()`
* Added `Message` object. When storing a message in `channel.messages`, it should be this type.
* The global `message_cache` is now a list instead of a hash. this allows a simpler format where the message json is just stored directly to disk and replayed via process_message.
* Removed `Meta` class.
* Removed `SlackThing` superclass.
* Added some documentation.
=> Backend refactor, Performance improvements, Reactions

README.md
just tried it out on one of my servers and those were the dependencies I had to install.
Thanks for an awesome weechat plugin!
=> add install instructions for FreeBSD

wee_slack.py
Let weechat know that we unloaded successfully and prevent a tiny bit
of whining on reload
=> Unload cleanly

wee_slack.py
Instead of using + to denote users present, use nick groups and label
them Present and Away.  Also, add all non-deleted users to the server
buffer.
I believe this should fix #72
=> Use nick lists for grouping here/away

wee_slack.py
This seems to solve #64 (at least on my system).
=> Fix unicode error in me_command_cb.

wee_slack.py
Add Bot entity to be able to get the name
Right now all the bots are represented as their ID:s which is not very
useful, this fixes this.
This is my first python code so please let me know if something is
weird.
=> Display name instead of ID for bots

wee_slack.py
Adds a version check right after script registration (must be registered to check the version).
Print an error if running version is < 1.3
=> check for minimum weechat version + error

wee_slack.py
=> check that channel has a buffer before sending typing notif

wee_slack.py
This allows a user to use either
`/slack topic [<#channel>] [topic]`
or
`/topic [<#channel>] [topic]` in a slack buffer to change the topic.
=> add code to do changes of topic.

wee_slack.py
Various updates to make the UI a tad better.
=> Bot and attachment formatting

wee_slack.py
=> always update the channels hashtable when we attach or detach a buffer

wee_slack.py
=> Respect weechat.look.nick_{suffix,prefix}

_pytest/test_unfurl.py, wee_slack.py
Digging into weird ``UnicodeDecodeException`` bugs I experienced, I ended up rewritting the ``unfurl_refs()`` function. 
Well, now itworks®
=> Rewrite ``unfurl_refs``

wee_slack.py
This makes the formatting of attachments somewhat more verbose and
makes it more similar to the web client. Downside is that it takes
more vertical space.
=> Format more fields from attachments

wee_slack.py
Thanks to @daurnimator and @trygveaa for patches this is built on.
Fixes: #122 
Obsoletes: #165
=> Pass system default ssl options to websocket.create_connection

wee_slack.py
=> new channels have # prepended as they should have

LICENSE
=> Add LICENSE file (MIT)

wee_slack.py
This should hopefully make some of the trello and other formatting a
bit better.
Fixes: #145
=> Add author_name to attachment formatting

wee_slack.py
set nick_$user for all buffer lines, and set log1 for message lines.
Fixes: #166
=> Add more tags to message lines

wee_slack.py
Some bots, such as lita (https://github.com/litaio/lita-slack) is
using the RTM API.  Those show up as regular users, but have is_bot
set on their user object.  Pick up on that when formatting lines.
Thanks to Whoop on IRC for pointing this out.
=> Handle bots using the RTM API too

wee_slack.py
Previous:
pagerduty :] | disabled an integration in this channel: https://…
Now:
pagerduty :] | foo disabled an integration in this channel: https://…
=> Print out the name of the user when enabling/disabling integrations

wee_slack.py
=> Check that a parameter is passed to /join

README.md
Also remove trailing whitespace on a few lines.
=> Add info on manually loading wee_slack.py when weechat is already running

wee_slack.py
that pass to their channel equivalents
=> Added process_group_join, process_group_leave and process_group_topic

wee_slack.py
I was unable to open queries to new people until this patch. I've been using it
for a few weeks and it seems stable.
=> Open new queries

wee_slack.py
This adds the `/command register` action, which lets you register for an oauth token.
=> add oauth code

wee_slack.py
This has a bunch of tiny changes, to satisfy the pep8 gods.
=> pep8 errything

wee_slack.py
=> add whitespace and anchors

wee_slack.py
=> use the correct colors for nick_prefix/nick_suffix

wee_slack.py
Tag string is being overwritten instead of appended.
=> Fix obvious mistake with tags

wee_slack.py
Various optimisations that make at least startup a lot faster for me.
=> Performance improvements

wee_slack.py
=> Format connection-info as unicode

wee_slack.py
I commented out this code because reasons. It is not reuncommented and unfurls work again.
=> yay for unfurls

wee_slack.py
Lots of missing whitespace and other minor fixups.
=> PEP8 fixups

wee_slack.py
Remove cache related bits and colorize_messages setting.
=> Clean up a little bit

wee_slack.py
=> Stop polling dead websockets.

wee_slack.py
This adds three new settings:
- `render_italic_as` controls how italics are rendered in weechat; it defaults to `italic` but if your terminal doesn't support that `underline` is recommended
- `render_bold_as` controls how bold is rendered
- `map_underline_to` controls how underlined text is sent to slack; the default is `_` (send as italics) but you may want to change it to `*` (bold) or even `` (nothing).
=> Add italic support, and settings to switch between italic and underline

wee_slack.py
I'm not super happy with the structure here, and ideally I'd like to just factor all the setting-related stuff into its own reusable library (but apparently multi-file plugins cause issues with weeslack?). I don't want to let the perfect be the enemy of the good here, though.
=> Add descriptions for weeslack plugin settings.

wee_slack.py
=> Fix AttributeError on /slack status in team buffer

wee_slack.py
=> Put users in groups according to presence

wee_slack.py
=> Update nicklist when team member presence changes

_pytest/conftest.py, _pytest/test_everything.py, _pytest/test_linkifytext.py, _pytest/test_presencechange.py, _pytest/test_process_message.py, _pytest/test_processreply.py, _pytest/test_processteamjoin.py, _pytest/test_sendmessage.py
This fixes the tests that are broken in master, and a few other minor changes.
@tfheen / @rawdigits: Want to enable Travis for this repo? I think you only need to flick the switch at https://travis-ci.org/profile/wee-slack (only admins can do so).
=> Fix broken tests

wee_slack.py
I chose to print this instead of using dbg since it's a rather critical
error message.
Fixes #432
=> Print error message when initial connection fails

wee_slack.py
While weechat plugins like multiline.pl and edit.py allow you to compose
multiline messages, wee-slack normally receives them line by line, so it
ends up as separate messages. There isn't any direct support for
receiving the complete message from weechat, but it can be done with
sort of a workaround.
There is a callback you can hook on to which allows you to intercept and
edit messages before they are sent to the buffer. This callback receives
the complete message with all the lines. By using this we can process
the whole message, and return an empty string from the callback which
means that the message will not be processed further.
Note that when this happens, weechat commands are not processed, which
is why we only use the callback for messages that contain a newline and
does not start …
=> Add support for sending multiline messages

README.md, wee_slack.py
This adds a few enhancements to the emoji completion:
- It adds custom emojis to the emoji completion list for each team.
- If `weemoji.json` is not found, it gives a better error message (Fixes #431)
- It adds documentation for enabling tab completion of emojis.
=> Add completion of custom emojis

wee_slack.py
https://api.slack.com/docs/presence-and-status#batching
=> Fix presence subscription now mandatory to get state changes

README.md
In #504 I proposed to add some help to future debuggers. This is a split PR from that.
cc: @trygveaa
=> debugging help

_pytest/conftest.py, wee_slack.py
=> Re-add support for weechat.look.nick_{prefix,suffix}

wee_slack.py
This now properly replaces spaces with underscores.
=> Fix nick sanitization

wee_slack.py
This seemed like a pretty sane way to handle this, at least for the near-term. @rawdigits mentioned wanting to do the whole thing differently, but until such time... This adds in the emoji alongside topic status text in the format:
`[:status_emoji:] status_text`
=> Add emojis to status as a DM topic

README.md, _pytest/test_unwrap_attachments.py, requirements.txt, wee_slack.py
https://github.com/hubotio/hubot prints image urls in the `attachment[]` array.
This prints them for clickability. Otherwise we just got the `title` which wasn't very useful.
=> print `image_url` if it exists

wee_slack.py
Remember the last nick printed and re-add support prefix_same_nick.
Fixes: #357
=> Re-add support for prefix_same_nick

wee_slack.py
This colorizes a bit "metatext" like "edited", "deleted" and reactions, to distinguish them visually from the real text.
=> Colorize edits and reactions

wee_slack.py
=> Add option to show thread messages in parent channel

wee_slack.py
This PR allows edition/deletion and reactions to messages in threads, by using the same mechanisms as the ones used for other channels.
I made both SlackChannel and SlackThreadChannel inherit from a common class SlackChannelCommon that will posess common methods (including the ones necessary for reactions and edition/deletion)
=> Allow reactions and edition of messages in threads

wee_slack.py
Similar to how Slack grays out muted channels in their own UI.
=> Gray out muted channels in buflist

README.md, wee_slack.py
This permits to select a message based on his id to /reply, edit, delete or "react" to a message. In "mouse" mode, clicking on a message pastes the id of the line in the input. In "cursor" mode, "M" permits to put the id of the line, "R" adds "/reply <id> ", and "D" deletes the line ("s///").
This PR is dependent on
https://github.com/wee-slack/wee-slack/pull/622
=> Select message cursor

wee_slack.py
This fixes the status call in case the user has no emoji or no status text defined
=> Fix status call

_pytest/test_linkifytext.py, wee_slack.py
=> Add apostrophe to the regex with a corresponding test

wee_slack.py
This ensures that changes to private channel membership are rendered correctly and update the user list.
=> Correctly handle group join/leave events

wee_slack.py
=> Expose more information in /whois

wee_slack.py
This allows setting `render_emoji_as_string` to `'both'`, showing both representations of emoji (`<emoji character> (:text-representation:)`), which allows one to at least see the text representation when their terminal doesn't render the emoji character.
=> Enable render_emoji_as_string = 'both'

wee_slack.py
This adds an optional -broadcast parameter to /reply and a /slack
broadcast command.
This should fix #491
=> Add ability to broadcast a thread message to the rest of the channel.

README.md, _pytest/conftest.py, _pytest/test_command_reply.py, docs/Commands.md, docs/Options.md, wee_slack.py
This fixes a bunch of issues with the handling of history.
=> Automatically reload history after reconnect

wee_slack.py
After connecting, IM channels that are open cause a buffer to be created, and any that are not open are skipped.  This results in direct messages being ignored when they have unread messages.
With this patch each closed IM channel is checked for unread messages and if any are found a buffer is created.
closes: #551
=> Check closed IM channels for unread messages

wee_slack.py
This PR display a link when a huddle is started.
Have a nice day :)
Regards
=> feat(huddle): Display link to join huddle when started

extract_token_from_browser.py
The extract_token_from_browser.py script does not handle Firefox containers
correctly. The container support works by namespacing cookies and local storage
with a 'userContextId'. In effect this means that when containers are used,
running the script will select the cookie from whichever container happens to be
returned first by the database query, which will be combined with the
non-containerised instance of the local storage.
Add correct handling by adding a new --container flag which specifies a
container either by numeric ID or by name, and including the correct
userContextId into the cookie query and local storage path (or excluding all
cookies from containers from the query if no --container flag is supplied).
With this the script can be run like:
python …
=> Handle Firefox containers in extract_token_from_browser.py

slack/commands.py, slack/error.py, slack/slack_api.py, slack/slack_user.py, typings/slack_api/slack_profile.pyi, typings/slack_api/slack_users_info.pyi
Adds the possibility to set the status message on the profile.
=> User profile
